### ISSUE TITLE
Change of the CAO namespaces

### ISSUE THREAD

**Issue by natasab** [CENDARI/litef-conductor#2]
The Cao Namespace and CAO ontology URI is at present 
http://cendari.eu/ontologies/cendari/cao

It should be changed to 

http://resources.cendari.dariah.eu/ontologies/cao

See https://wiki.de.dariah.eu/pages/viewpage.action?title=URI+Conventions+for+Data+and+Resources+in+Cendari+Virtuoso&spaceKey=CENDARI

**Comment by ivan-cukic** [comment]
done
