### ISSUE TITLE
Ontology files are uploaded as graph resources, but ontology content is not uploaded to Virtuoso

### ISSUE THREAD

**Issue by natasab** [CENDARI/litef-conductor#3]
As in description..

select *
where {http://resources.cendari.dariah.eu/resources/b0bfcbf2-7421-4fcc-aaa1-e367d6a488cb ?p ?o}

no other resource uploaded

**Comment by ivan-cukic** [comment]
Virtuoso did not understand the cendari: prefix to point to cao. I'm using the full path now.

**Comment by ivan-cukic** [comment]
p.s. The query in the bug report was wrong - it needs to list the resources in the graph G, not to ask for { G ?p ?o }, and URL needs to be in brackets <url>.

```
select * where {
    graph <http://resources.cendari.dariah.eu/resources/b0bfcbf2-7421-4fcc-aaa1-e367d6a488cb> {
        ?s ?v ?o
    }
}
```

**Comment by natasab** [comment]
Btw. GitHub makes the formatting, query is fine, with or without graph notation..

**Comment by ivan-cukic** [comment]
It is not the same query:

```
select * { G ?v ?o } -- returns 'info' about the graph -- this will never show that the ontology content is loaded
```

and

```
select * { graph G { ?s ?v ?o } } -- return info in the graph
```

**Comment by natasab** [comment]
Hm... i tried both alternatives, and they give me almost same result for WW1 LOD on int2 e.g.

```
select *  where { graph <http://resources.cendari.dariah.eu/resources/56ed20f4-e429-4a89-a081-015ba9a181b4> { ?s ?v ?o } }
```

does not give me LOD WW1 data  either..

https://int2.cendari.dariah.eu/ckan/dataset/ww1-lod/resource/56ed20f4-e429-4a89-a081-015ba9a181b4

What i do wrong?

**Comment by ivan-cukic** [comment]
This is from the log for that resource (I guess it is again the issue with ckan NFS being available):
java.io.FileNotFoundException: /mnt/storage/CENDARI/TESTAPI/resources/56e/d20/f4-e429-4a89-a081-015ba9a181b4 (Permission denied)

**Comment by natasab** [comment]
this is again permission issue or?

**Comment by natasab** [comment]
one ontology file is loaded, but the other is not .. strange.

**Comment by ivan-cukic** [comment]
> this is again permission issue or?

Yes. The NFS goes berserk from time to time. It is either that, or file permissions are wrong, or (less likely given the message) that the file does not exist.

**Comment by natasab** [comment]
@schildwaechter please check ..

**Comment by natasab** [comment]
question: in the exmaple provided ..

```
 select * where {
graph <http://resources.cendari.dariah.eu/resources/b0bfcbf2-7421-4fcc-aaa1-e367d6a488cb> {
    ?s ?v ?o
}
```

}

I see mentions and all what is in document graph. But i do not see ontologies in triples..
How to do it?

**Comment by ivan-cukic** [comment]
I've restarted indexing. Will look into it when it finishes.

**Comment by ivan-cukic** [comment]
b0b was reindexed - it shows the ontology contents as well
