### ISSUE TITLE
Fix encoding of NERD Uris

### ISSUE THREAD

**Issue by natasab** [CENDARI/litef-conductor#4]
Check where encoding of files (and if) becomes broken. 
On download it JSON file shows ISO-8859 character set, and it is further treated as such.
This produces very strange URIs and values afterwards in NERD.

https://int2.cendari.dariah.eu/ckan/dataset/9200316-bibliographicresource_3000092750591/resource/4a24a665-1bed-4a8c-bd97-77b67d8ac351

the RDF version of this resource is in UTF encoding, see 
https://int2.cendari.dariah.eu/ckan/dataset/9200316-bibliographicresource_3000092750591/resource/f22c70aa-c640-4773-884d-076ac2f536c4

on download UTF-8 file, somewhere during processing (i could track to NERD2RDF processing) the encoding goes into ascii

nbulatovic@int2:/var/lib/litef/default/resources/f22/c70/aa-c640-4773-884d-076ac2f536c4$ file application:rdf+xml
application:rdf+xml: UTF-8 Unicode text, with very long lines

nbulatovic@int2:/var/lib/litef/default/resources/f22/c70/aa-c640-4773-884d-076ac2f536c4$ file application:x-nerd-output
application:x-nerd-output: UTF-8 Unicode text, with very long lines, with no line terminators

nbulatovic@int2:/var/lib/litef/default/resources/f22/c70/aa-c640-4773-884d-076ac2f536c4$ file "application:x-nerd-output -> application:rdf+xml"
application:x-nerd-output -> application:rdf+xml: ASCII text

**Comment by ivan-cukic** [comment]
> This produces very strange URIs and values afterwards in NERD.

As requested previously by JD, all URIs are URL-encoded to ASCII instead of using IRIs.

**Comment by natasab** [comment]
I do not think this is invalid issue - URI encoding to ASCII is one issue, but the same problem appears with the values e.g. if a Person - Name  of person - this does not mean the whole file should change the encoding.

**Comment by ivan-cukic** [comment]
The name encoding is a separate issue. This one is about Uris, and the issue description talks about URIs. 

Name values are not stored in the 'application:x-nerd-output -> application:rdf+xml'.

The name issue came to existence since the change to move all entities to a separate graph - so they no longer apear in the above specified file.

I've opened #5 to handle that
