### ISSUE TITLE
Wrong encoding of string values returned by NERD stored in Virtuoso

### ISSUE THREAD

**Issue by ivan-cukic** [CENDARI/litef-conductor#5]
The following returns junk for non-ascii names:
select ?o { graph http://resources.cendari.dariah.eu/entitiesGraph { ?s ?v ?o } }

**Comment by ivan-cukic** [comment]
Works on dev3

```
select * { 
    <http://resources.cendari.dariah.eu/persons/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE> ?v ?o 
}

 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://schema.org/Person
 -> http://schema.org/name "Начало"^^<http://www.w3.org/2001/XMLSchema#string>
```

It fails on int2 for some reason.

@natasab @schildwaechter any ideas? Both versions use -Dfile.encoding=UTF-8

(p.s. ignore that NERD thinks 'start' in Russian is a person)

**Comment by natasab** [comment]
I could only ask if you may check if the Virtuoso database encoding is 
same both on int2 and dev?
Also, we should check OS locale and collating on both servers..
Other - do not know :)
(In train to munich) ..

On 23.11.2015 18:34, Ivan Čukić wrote:

> Works on dev3
> 
> |select \* { 
> http://resources.cendari.dariah.eu/persons/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE 
> ?v ?o } -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type 
> http://schema.org/Person -> http://schema.org/name 
> "Начало"^^http://www.w3.org/2001/XMLSchema#string |
> 
> It fails on int2 for some reason.
> 
> @natasab https://github.com/natasab @schildwaechter 
> https://github.com/schildwaechter any ideas?
> 
> (p.s. ignore that NERD thinks 'start' in Russian is a person)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CENDARI/litef-conductor/issues/5#issuecomment-159005575.

## 

## 

Natasa Bulatovic
Max Planck Digital Library (MPDL)
Amalienstrasse 33
80799 Munich, Germany
http://www.mpdl.mpg.de

e-Mail: bulatovic@mpdl.mpg.de
phone: +49-89-38602-223
fax: +49-89-38602-280

**Comment by ivan-cukic** [comment]
This is dev:

```
LANG=en_US.UTF-8
LC_ALL=POSIX
```

This is int:

```
LC_ALL=en_GB.UTF-8
LANG=en_US.UTF-8
LANGUAGE=en_US:en
```

I have no idea what is used where :)

(have a nice trip)

**Comment by mikesname** [comment]
I'm not sure what changed, but the data on int2 looks fine to me now... :smile:

**Comment by ivan-cukic** [comment]
The reindexing was done with the above vars set. But it is a temporary solution until sysadmins actually change them permanently.

(I'll close the report when that happens)
